// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddressInput struct {
	Street string `json:"Street"`
	State  string `json:"State"`
	City   string `json:"City"`
}

type CreateUserInput struct {
	Name       string        `json:"name"`
	Password   string        `json:"password"`
	Email      string        `json:"email"`
	DocumentNo string        `json:"documentNo"`
	Address    *AddressInput `json:"address"`
	BirthDate  *Date         `json:"birthDate"`
}

type CreateUserOutput struct {
	UserID string `json:"userID"`
}

type Date struct {
	Year  *int    `json:"year,omitempty"`
	Month *string `json:"month,omitempty"`
	Day   *int    `json:"day,omitempty"`
}
